version: "3"
services:
  raftproxy: 
    image: haproxy-raft-img
    container_name: haproxy_raft_cont
    hostname: ${HOSTNAME}
    build:
      context: ../../
      dockerfile: ./lb/Dockerfile.raft.lb
    volumes:
      - ../../certs:/certs
    ports: 
      - '443:443'
    networks:
      raft_api_network:
    depends_on:
      - raftsrv1
      - raftsrv2
      - raftsrv3
      - raftsrv4
      - raftsrv5
  raftsrv1:
    image: raftsrv1_img
    container_name: raftsrv1_cont
    hostname: raftsrv1
    build:
      context: ../../
      dockerfile: ./cmd/raft/Dockerfile
    networks:
      raft_api_network:
    ports:
      - 8080
      - 54321
      - 54322
      - 54323
      - 54324
    volumes:
      - $HOME/raftsrv1/replog:/home/raft/replog
      - $HOME/raftsrv1/statemachine:/home/raft/statemachine
  raftsrv2:
    image: raftsrv2_img
    container_name: raftsrv2_cont
    hostname: raftsrv2
    build:
      context: ../../
      dockerfile: ./cmd/raft/Dockerfile
    networks:
      raft_api_network:
    ports:
      - 8080
      - 54321
      - 54322
      - 54323
      - 54324
    volumes:
      - $HOME/raftsrv2/replog:/home/raft/replog
      - $HOME/raftsrv2/statemachine:/home/raft/statemachine
  raftsrv3:
    image: raftsrv3_img
    container_name: raftsrv3_cont
    hostname: raftsrv3
    build:
      context: ../../
      dockerfile: ./cmd/raft/Dockerfile
    networks:
      raft_api_network:
    ports:
      - 8080
      - 54321
      - 54322
      - 54323
      - 54324
    volumes:
      - $HOME/raftsrv3/replog:/home/raft/replog
      - $HOME/raftsrv3/statemachine:/home/raft/statemachine
  raftsrv4:
    image: raftsrv4_img
    container_name: raftsrv4_cont
    hostname: raftsrv4
    build:
      context: ../../
      dockerfile: ./cmd/raft/Dockerfile
    networks:
      raft_api_network:
    ports:
      - 8080
      - 54321
      - 54322
      - 54323
      - 54324
    volumes:
      - $HOME/raftsrv4/replog:/home/raft/replog
      - $HOME/raftsrv4/statemachine:/home/raft/statemachine
  raftsrv5:
    image: raftsrv5_img
    container_name: raftsrv5_cont
    hostname: raftsrv5
    build:
      context: ../../
      dockerfile: ./cmd/raft/Dockerfile
    networks:
      raft_api_network:
    ports:
      - 8080
      - 54321
      - 54322
      - 54323
      - 54324
    volumes:
      - $HOME/raftsrv5/replog:/home/raft/replog
      - $HOME/raftsrv5/statemachine:/home/raft/statemachine
networks:
  raft_api_network:
    driver: bridge