version: "3"
services:
  raftsrv1:
    image: raftsrv1_img
    container_name: raftsrv1_cont
    hostname: raftsrv1
    build:
      context: ../../
      dockerfile: ./cmd/raft/Dockerfile
    networks:
      raft_api_network:
    ports:
      - 54321
      - 54322
      - 54323
      - 54324
    volumes:
      - $HOME/raftsrv1:/home/raft/replog
  raftsrv2:
    image: raftsrv2_img
    container_name: raftsrv2_cont
    hostname: raftsrv2
    build:
      context: ../../
      dockerfile: ./cmd/raft/Dockerfile
    networks:
      raft_api_network:
    ports:
      - 54321
      - 54322
      - 54323
      - 54324
    volumes:
      - $HOME/raftsrv2:/home/raft/replog
  raftsrv3:
    image: raftsrv3_img
    container_name: raftsrv3_cont
    hostname: raftsrv3
    build:
      context: ../../
      dockerfile: ./cmd/raft/Dockerfile
    networks:
      raft_api_network:
    ports:
      - 54321
      - 54322
      - 54323
      - 54324
    volumes:
      - $HOME/raftsrv3:/home/raft/replog
  raftsrv4:
    image: raftsrv4_img
    container_name: raftsrv4_cont
    hostname: raftsrv4
    build:
      context: ../../
      dockerfile: ./cmd/raft/Dockerfile
    networks:
      raft_api_network:
    ports:
      - 54321
      - 54322
      - 54323
      - 54324
    volumes:
      - $HOME/raftsrv4:/home/raft/replog
  raftsrv5:
    image: raftsrv5_img
    container_name: raftsrv5_cont
    hostname: raftsrv5
    build:
      context: ../../
      dockerfile: ./cmd/raft/Dockerfile
    networks:
      raft_api_network:
    ports:
      - 54321
      - 54322
      - 54323
      - 54324
    volumes:
      - $HOME/raftsrv5:/home/raft/replog
networks:
  raft_api_network:
    driver: bridge